packages:
  - packages/*

catalog:
  rollup-plugin-visualizer: ^5.14.0
  typescript: ^5.9.3
  vite: ^7.1.12
  vite-plugin-dts: ^4.5.4
  vitest: ^4.0.6

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
