packages:
  - packages/*

catalog:
  typescript: ^5.9.3
  vite: ^7.1.12
  vitest: ^4.0.6
  vite-plugin-dts: ^4.5.4
  rollup-plugin-visualizer: ^5.14.0

onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
