packages:
  - packages/*

catalog:
  typescript: ^5.7.3
  vite: ^6.1.0
  vitest: ^3.0.5
  vite-plugin-dts: ^4.5.0
  rollup-plugin-visualizer: ^5.14.0

onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
