packages:
  - packages/*

catalog:
  typescript: ^5.8.3
  vite: ^6.3.5
  vitest: ^3.1.4
  vite-plugin-dts: ^4.5.4
  rollup-plugin-visualizer: ^5.14.0

onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
